#!/usr/bin/env bash
set -e

echo "╔════════════════════════════════════════════╗"
echo "║  Pi-hole AI Guardian Setup Wizard          ║"
echo "╚════════════════════════════════════════════╝"
echo ""

# Prompt for configuration
read -p "SSH Username (current: $USER): " -r SSH_USER
SSH_USER=${SSH_USER:-$USER}

read -p "Pi-hole IP or hostname [192.168.68.104]: " -r PIHOLE_IP
PIHOLE_IP=${PIHOLE_IP:-192.168.68.104}

read -sp "Pi-hole Admin Password: " PIHOLE_PASSWORD
echo ""
read -sp "Pi-hole Admin Password (confirm): " PIHOLE_PASSWORD_CONFIRM
echo ""
if [[ "$PIHOLE_PASSWORD" != "$PIHOLE_PASSWORD_CONFIRM" ]]; then
    echo "ERROR: Passwords don't match"
    exit 1
fi

read -p "Installation directory [$HOME/pihole-ai]: " -r INSTALL_DIR
INSTALL_DIR=${INSTALL_DIR:-$HOME/pihole-ai}

read -p "Ollama API URL [http://localhost:11434]: " -r OLLAMA_URL
OLLAMA_URL=${OLLAMA_URL:-http://localhost:11434}

read -p "Ollama Model [granite3.3:2b]: " -r OLLAMA_MODEL
OLLAMA_MODEL=${OLLAMA_MODEL:-granite3.3:2b}

PIHOLE_CMD=$(command -v pihole || true)
PIHOLE_CMD=${PIHOLE_CMD:-/usr/local/bin/pihole}

echo ""
echo "Configuration Summary:"
echo "  SSH User: $SSH_USER"
echo "  Pi-hole IP: $PIHOLE_IP"
echo "  Install Dir: $INSTALL_DIR"
echo "  Ollama URL: $OLLAMA_URL"
echo "  Ollama Model: $OLLAMA_MODEL"
echo ""
read -p "Continue? (y/n): " -r CONFIRM
if [[ "$CONFIRM" != "y" ]]; then
    echo "Cancelled."
    exit 0
fi

# Create install directory and venv
echo ""
echo "Creating installation directory..."
mkdir -p "$INSTALL_DIR/tests/fixtures" "$INSTALL_DIR/logs"

echo "Creating Python venv..."
python3 -m venv "$INSTALL_DIR/.venv"

echo "Installing dependencies..."
"$INSTALL_DIR/.venv/bin/pip" install -q requests==2.32.3 watchdog==4.0.1 pytest

cd "$INSTALL_DIR"

# Generate config_local.py
echo "Generating config_local.py..."
cat > config_local.py << 'EOFCONFIG'
# Auto-generated by setup.sh — do not edit directly
import os

SSH_USER = "SSH_USER_PLACEHOLDER"
PIHOLE_IP = "PIHOLE_IP_PLACEHOLDER"
PIHOLE_PASSWORD = "PIHOLE_PASSWORD_PLACEHOLDER"
INSTALL_DIR = "INSTALL_DIR_PLACEHOLDER"
OLLAMA_URL = "OLLAMA_URL_PLACEHOLDER"
OLLAMA_MODEL = "OLLAMA_MODEL_PLACEHOLDER"

# Derived paths
BASE_DIR = INSTALL_DIR
STATE_DB_PATH = os.path.join(BASE_DIR, "state.db")
LOG_DIR = os.path.join(BASE_DIR, "logs")
PIHOLE_DB_PATH = "/etc/pihole/gravity.db"
FTL_LOG_PATH = "/var/log/pihole/pihole.log"
PIHOLE_RELOAD_CMD = "sudo -n PIHOLE_CMD_PLACEHOLDER reloadlists"
PIHOLE_RELOAD_INTERVAL_SECONDS = 60

# Override config defaults
OLLAMA_BASE_URL = OLLAMA_URL
EOFCONFIG

# Substitute variables
sed -i.bak "s|SSH_USER_PLACEHOLDER|$SSH_USER|g" config_local.py
sed -i.bak "s|PIHOLE_IP_PLACEHOLDER|$PIHOLE_IP|g" config_local.py
sed -i.bak "s|PIHOLE_PASSWORD_PLACEHOLDER|$PIHOLE_PASSWORD|g" config_local.py
sed -i.bak "s|INSTALL_DIR_PLACEHOLDER|$INSTALL_DIR|g" config_local.py
sed -i.bak "s|OLLAMA_URL_PLACEHOLDER|$OLLAMA_URL|g" config_local.py
sed -i.bak "s|OLLAMA_MODEL_PLACEHOLDER|$OLLAMA_MODEL|g" config_local.py
sed -i.bak "s|PIHOLE_CMD_PLACEHOLDER|$PIHOLE_CMD|g" config_local.py
rm -f config_local.py.bak

echo "✓ config_local.py created"

# Generate systemd service from template
echo "Generating systemd service..."
if [[ -f "$INSTALL_DIR/pihole-ai.service.tpl" ]]; then
    sed -e "s|\$SSH_USER|$SSH_USER|g" \
        -e "s|\$INSTALL_DIR|$INSTALL_DIR|g" \
        "$INSTALL_DIR/pihole-ai.service.tpl" > "$INSTALL_DIR/pihole-ai-$SSH_USER.service"

    echo "Installing systemd service..."
    sudo cp "$INSTALL_DIR/pihole-ai-$SSH_USER.service" /etc/systemd/system/
    sudo systemctl daemon-reload
    sudo systemctl enable "pihole-ai-$SSH_USER"

    # Allow user to write to gravity.db and run reloadlists
    SUDOERS_LINE="$SSH_USER ALL=(ALL) NOPASSWD: $PIHOLE_CMD reloadlists, $PIHOLE_CMD reloaddns"
    if ! sudo grep -qF "$SUDOERS_LINE" "/etc/sudoers.d/pihole-ai-$SSH_USER" 2>/dev/null; then
        echo "$SUDOERS_LINE" | sudo tee "/etc/sudoers.d/pihole-ai-$SSH_USER" > /dev/null
        sudo chmod 0440 "/etc/sudoers.d/pihole-ai-$SSH_USER"
        echo "✓ Sudoers rule created"
    fi

    # Fix permissions on Pi-hole directory and files
    echo "Fixing permissions on Pi-hole..."
    if command -v setfacl &> /dev/null; then
        # Set ACLs on /etc/pihole directory and files
        [[ -d "/etc/pihole" ]] && sudo setfacl -m u:"$SSH_USER":rwx /etc/pihole/
        [[ -f "/etc/pihole/gravity.db" ]] && sudo setfacl -m u:"$SSH_USER":rw /etc/pihole/gravity.db
        [[ -f "/etc/pihole/versions" ]] && sudo setfacl -m u:"$SSH_USER":rw /etc/pihole/versions
        [[ -d "/var/log/pihole" ]] && sudo setfacl -m u:"$SSH_USER":rx /var/log/pihole/
        [[ -f "/var/log/pihole/pihole.log" ]] && sudo setfacl -m u:"$SSH_USER":r /var/log/pihole/pihole.log
        echo "✓ ACL permissions set"
    else
        # Fallback: use chmod
        [[ -d "/etc/pihole" ]] && sudo chmod o+rx /etc/pihole/
        [[ -f "/etc/pihole/gravity.db" ]] && sudo chmod o+rw /etc/pihole/gravity.db 2>/dev/null || true
        [[ -f "/etc/pihole/versions" ]] && sudo chmod o+rw /etc/pihole/versions 2>/dev/null || true
        [[ -d "/var/log/pihole" ]] && sudo chmod o+rx /var/log/pihole/ 2>/dev/null || true
        [[ -f "/var/log/pihole/pihole.log" ]] && sudo chmod o+r /var/log/pihole/pihole.log 2>/dev/null || true
        echo "✓ File permissions set"
    fi

    echo "Starting daemon..."
    sudo systemctl start "pihole-ai-$SSH_USER"
fi

# Git init
if [[ ! -d .git ]]; then
    git init
    git config user.email "pihole-ai@localhost"
    git config user.name "Pi-hole AI Guardian"
    git add requirements.txt setup.sh config_local.py 2>/dev/null || true
    git commit -m "Initial commit" 2>/dev/null || true
fi

echo ""
echo "✓ Setup complete!"
echo ""
echo "Status and logs:"
echo "  sudo systemctl status pihole-ai-$SSH_USER"
echo "  sudo journalctl -u pihole-ai-$SSH_USER -f"
echo "  tail -f $INSTALL_DIR/logs/pihole-ai.log"
echo ""
